[package]
name = "drawio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indented = "0.1.0"
srp = { git = "https://github.com/perlindgren/srp-analysis.git" }
# srp = { path = "../srp-analysis" }
